sonar.projectKey=laxminarsimha01_8.2CDevSecOps
sonar.organization=laxminarsimha01
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=node_modules/**,test/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
